# Generated by Django 2.2.7 on 2022-02-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj1', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='media/profile_pics'),
        ),
    ]
